### ISSUE TITLE
Bedrockify support

### ISSUE THREAD

**Issue by antieksi** [csumpasd/segmented#10]
Bedrockify has that interesting feature called «Screen safe area» which moves the hotbar up. Would like to use it with this mod.

![изображение](https://github.com/csumpasd/segmented/assets/95758843/6337b3ec-3d73-41a0-9e67-f6da99146c80)

**Comment by csumpasd** [comment]
I'll look into it!

**Comment by csumpasd** [comment]
I looked hard into bedrockify's code, and didn't find any reasonably simple way to inject into it. 
segmented supports raised (https://modrinth.com/mod/raised), so if you want this functionality, it's available through that mod.
