### ISSUE TITLE
Support for older versions?

### ISSUE THREAD

**Issue by WimpieRatte** [csumpasd/segmented#5]
Would've loved to load this immediately into my 1.19.2 modpack. :D

Could you mention in your mod description whether or not you have plans for older versions, like 1.19.2?

**Comment by csumpasd** [comment]
Hi! I'm happy you like the mod! :D 
I didn't have plans for older versions, but I'm pretty sure it wouldn't be hard to port it for those. 

I have a few exams early next week I have to prepare for, but I'll start porting it to all 1.19 versions after, and I'll start with 1.19.2, so you can play as early as possible. Sounds good?

**Comment by WimpieRatte** [comment]
hehe. sounds awesome :D.
I followed the mod on Modrinth already (so I'll get notified of your update) and already added it to my clientside-only modpack.
I'll add the 1.19.2 version to my bigger modpack when you publish it :D.

Well done on doing this mod! I recently was so annoyed by needing to always scroll or reach far to the higher hotbar buttons.
So the timing of this mod is really good.

Gonna try it in a combination with Switcheroo, AutoHUD and Slot Cycler :).

**Comment by csumpasd** [comment]
Thanks for the kind words! The idea is not mine though, I just wanted to finally get to learning modding, and make this as a simple client mod. Check out https://github.com/Lizard-Of-Oz/Inventorio, it does the same idea and much more, although it's not client-only.

**Comment by WimpieRatte** [comment]
oh wow. Haven't seen that before! VEEEERY good ideas he has there :D.

**Comment by csumpasd** [comment]
yep :D

**Comment by csumpasd** [comment]
heyyo, sorry for the long wait, exams hit me harder than expected and I couldn't work on the project in spite of my hopes, but I just finished v0.3.0 with some much needed compat and refactoring, and I'm now going to do the whole 1.19-1.20 lineup. Hoping to release all these in like a day :D

**Comment by csumpasd** [comment]
ported it to 1.19.2 and the twenties, but I think I'll hold off on others because it's useless work if nobody wants it

**Comment by WimpieRatte** [comment]
Thank you very much!!! :D
Using it now :D
