### ISSUE TITLE
Compatibility with AutoHUD?

### ISSUE THREAD

**Issue by WimpieRatte** [csumpasd/segmented#6]
Currently, when running this with AutoHUD (a mod that automatically displays/hides your HUD), it doesn't trigger the HUD re-appearing until you press the second button in the sequence.
Would be nice if the first press of the sequence already brings up the HUD.

I realise this is probably an upgrade that AutoHUD can build compatiblity with for your mod as well, but perhaps there's a way for your mod to signal a false positive hotbar change, which AutoHUD would detect during the first button press?

**Comment by csumpasd** [comment]
will look into it

**Comment by csumpasd** [comment]
note to self on this: i'm guessing autohud injects into the hotbar selection, so just telling the game to re-select the same slot might work, although that might cause other issues

**Comment by WimpieRatte** [comment]
Another thought:
It also has a shortcut key for unhiding while the key is being pressed down.
Perhaps that can be triggered instead until the 2nd button is pressed? (If the mod is detected to be installed.)
(So it has a functions that can reveal itself without necessarily changing the hotbar selection.)

**Comment by csumpasd** [comment]
working in v0.3.0 (also, the default timings of segmented work so well with autohud, check it out :D)

**Comment by WimpieRatte** [comment]
Confirmed and enjoying it. Thanks!!! :D
