### ISSUE TITLE
Can't distinguish first selection with vanilla hotbar rendering

### ISSUE THREAD

**Issue by antieksi** [csumpasd/segmented#8]
I don't like the look of the vanilla HUD and because of this I always use resourcepacks. However, with vanilla hotbar rendering enabled, it's hard to understand when I had pressed button to change the slot or not. Can there be some temporary fix for this, maybe a number above the hotbar that shows when the first key is pressed?

I'd like to see support for custom hotbars using resourcepacks in the future. Thanks.

**Comment by csumpasd** [comment]
I'll look into adding something like you suggested. 

There is custom hotbar support using resource packs by default, just like any other mod. You have to put the desired hotbar png file into /assets/segmented/gui/widgets.png in your resource pack. The layout of the png should match the default one in the github repository under the same path. 

If you're talking about stitching the texture together from the vanilla hotbar, then I have thought of that too, and it's on the timeline, but it's definitely not a feature I can add anytime soon.

**Comment by antieksi** [comment]
Custom hotbar resourcepack didn't work. Not sure if I am doing something wrong.

**Comment by antieksi** [comment]
So, I tried using resourcepack and it didn't work. Am I doing something wrong? [Here's the png](https://i.imgur.com/v38XZ6Z.png) I made based on layout.

And that reopen was a misclick.

**Comment by csumpasd** [comment]
ahh, my bad, the correct path is /assets/segmented/textures/gui/widgets.png, similar to the minecraft widgets.png

I'm using my own resource pack, that's why i'm so sure it works :D

I'm not certain, but your single slot selector seems misaligned in the png, so if it is, then just remove the gap between that and the segment selector. Otherwise, it looks good.

**Comment by antieksi** [comment]
Works now. Thanks!

**Comment by csumpasd** [comment]
modified the texture format in v0.3.0, you can find the updated one in the same location. Sorry for the trouble, it makes my life way easier for the roadmap
