### ISSUE TITLE
Keep 4-9 slot keybinds

### ISSUE THREAD

**Issue by Felix14-v2** [csumpasd/segmented#9]
It would be nice if Segmented did not remove the ability to select slots directly using other vanilla keys. For example, I use the side buttons on my mouse to select slots 5 and 9, and it's pretty convenient. However, with this mod, I can't use them anymore.

**Comment by csumpasd** [comment]
sure, i'll add an option for that in the next version.

**Comment by csumpasd** [comment]
done, now it's the default, you can unbind 4-9 to get the old mechanics anyways
